language: minimal # maybe cpp

services:
  - docker

before_install:
  - docker pull mrkibk/systemc-verilator:1.2
  - docker build -t systemc-verilator-tb .
  - docker run -d systemc-verilator-tb /bin/sh -c "make"

# script:
#   - bundle exec rake test
