sudo: required

# Not sure if these are needed
# language: minimal # maybe cpp
# dist: trusty

services:
  - docker

install:
  - docker pull mrkibk/systemc-verilator:1.5 || true
  - docker build --tag systemc-verilator-tb .

# before_script:


script:
  - docker run -it --rm --name testbench systemc-verilator-tb make
  - exit

# script:
#   - bundle exec rake test
